#!/usr/bin/env python3
"""
Generate the binary-STL geometry for the `dorm_room` GADEN scenario.

GADEN's preprocessing voxelises meshes with a triangle/box separating-axis
test and then flood-fills the free space from `empty_point`, so only the
geometry matters — the per-triangle normals stored in the STL are ignored.
Re-run this script after editing the dimensions below to regenerate the CAD:

    python3 test_env/scripts/make_dorm_geometry.py

Layout (metres, origin at the lower-left corner, matching the floor-plan sketch):

    +Y (7.0) +-[ wardrobe ]-=== window ===---------------------+
             |                                                 |
             |                                                 |  CO2 vents up
             |                                                 |  to the window
             |                                                 |  and spreads
             |                   * fire / CO2  (3.80, 1.80)    |  through the room
             |                 ^ start (2.70, 0.60)            |
       (0,0) +-------------------------------------------------+ +X (5.4)
"""
import os
import struct

# --- Geometry (metres) -------------------------------------------------
T = 0.20            # wall thickness (>= 2 cells @ 0.1 m -> watertight barrier)
H = 2.40            # room height
X1, Y1 = 5.40, 7.00  # outer extents (Y1 = bottom->top length)

# "Open window" opening on the TOP wall (top-left region of the room)
WIN_X0, WIN_X1 = 1.90, 2.90

# Solid structure boxes: (x0, x1, y0, y1, z0, z1)
WALLS = [
    (0.0,    X1,     0.0,    T,    0.0, H),   # bottom wall
    (0.0,    WIN_X0, Y1 - T, Y1,   0.0, H),   # top wall  (left of window)
    (WIN_X1, X1,     Y1 - T, Y1,   0.0, H),   # top wall  (right of window)
    (0.0,    T,      0.0,    Y1,   0.0, H),   # left wall
    (X1 - T, X1,     0.0,    Y1,   0.0, H),   # right wall
    (T,      1.60,   Y1 - T - 1.20, Y1 - T, 0.0, H), # wardrobe (top-left obstacle, pinned to top wall)
]

# Window outlet plate -- seals the top-wall gap as a GADEN outlet (open vent)
WINDOW = [
    (WIN_X0, WIN_X1, Y1 - T, Y1, 0.0, H),
]


def _box_triangles(x0, x1, y0, y1, z0, z1):
    """Return the 12 triangles (as 3-tuples of vertices) covering a box."""
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    quads = [
        (0, 1, 2, 3),  # bottom  (z0)
        (4, 5, 6, 7),  # top     (z1)
        (0, 4, 5, 1),  # -y face
        (3, 2, 6, 7),  # +y face
        (0, 3, 7, 4),  # -x face
        (1, 5, 6, 2),  # +x face
    ]
    tris = []
    for a, b, c, d in quads:
        tris.append((v[a], v[b], v[c]))
        tris.append((v[a], v[c], v[d]))
    return tris


def _normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    m = (nx * nx + ny * ny + nz * nz) ** 0.5 or 1.0
    return (nx / m, ny / m, nz / m)


def write_stl(path, boxes, header="GADEN dorm_room generated by make_dorm_geometry.py"):
    tris = []
    for box in boxes:
        tris += _box_triangles(*box)
    with open(path, 'wb') as f:
        f.write(header.encode('ascii', 'replace')[:80].ljust(80, b'\0'))
        f.write(struct.pack('<I', len(tris)))
        for a, b, c in tris:
            n = _normal(a, b, c)
            f.write(struct.pack('<12fH',
                                n[0], n[1], n[2],
                                a[0], a[1], a[2],
                                b[0], b[1], b[2],
                                c[0], c[1], c[2], 0))
    return tris


def _bounds(boxes):
    xs = [b[i] for b in boxes for i in (0, 1)]
    ys = [b[i] for b in boxes for i in (2, 3)]
    zs = [b[i] for b in boxes for i in (4, 5)]
    return (min(xs), max(xs)), (min(ys), max(ys)), (min(zs), max(zs))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    cad = os.path.normpath(os.path.join(here, '..', 'scenarios', 'dorm_room', 'cad_models'))
    os.makedirs(cad, exist_ok=True)

    walls_path = os.path.join(cad, 'walls.stl')
    window_path = os.path.join(cad, 'window.stl')
    wt = write_stl(walls_path, WALLS)
    nt = write_stl(window_path, WINDOW)

    print(f"walls.stl : {len(wt)} triangles  bounds={_bounds(WALLS)}  -> {walls_path}")
    print(f"window.stl: {len(nt)} triangles  bounds={_bounds(WINDOW)}  -> {window_path}")
    print("Done. Run GADEN preprocessing to voxelise into occupancy.")


if __name__ == '__main__':
    main()
